[create-image-planar]
field-size-mm = [100.0, 100.0]
sigma-mm = 2.0
gantry-angle = 0.0
epid = "iViewGT"

[analyze-preliminary]
input-dir = "samples"
output-dir = "tests"
input-preffix = "preliminary"
output-preffix = "output"
filetype = "csv"
summary = "summary.json"
default-basetypes = ["int", "float", "float", "float", "float", "float"]
column-class = ["index", "T", "P", "m", "k_TP", "m_corrected"]
new-input-units = ["unit", "C", "mbar", "nC", "unit", "nC"]
new-output-units = ["unit", "C", "mbar", "nC", "unit", "nC"]
max-PTP = 1.2

[analyze-image-planar]
protocol = "elekta"
output = "image-report.pdf"

[generate-calibration-report]
output = "calibration-report.pdf"
chamber = "30013"
clinical-pdd-zref = 66.5
energy = 6
fff = false
institution = "Hospital Oncológico Dr. Miguel Pérez Carreño"
k-elec = 1.000
m-opposite = [25.64, 25.65, 25.65]
m-reference = [25.65, 25.66, 25.65]
m-reduced = [25.64, 25.63, 25.63]
measurement-date = "2025-05-16"
mu = 200
n-dw = 5.443
physicist = "Lic. Nelson Sandoval Puente"
press = 100.65839
setup = "SSD"
temp = 22.1
tissue-correction = 1.0
tpr2010 = 0.573573574
unit = "Elekta Precise"
voltage-reduced = -150
voltage-reference = -300
notes = "Sample note."

[generate-graph]
output = "graph_output.png"
figsize = { x = 10, y = 6 }
marker = "."
linestyle = "-"
title = "Titulo"
grid = true
