[analyze-preliminary]
input-dir = "samples"
output-dir = "tests"
input-preffix = "preliminary"
output-preffix = "output"
filetype = "csv"
summary = "summary.json"
default-base-types = ""
new-input-units = ""
output-units = ""
max-PTP = ""

[generate-calibration-report]
output = "calibration_report.pdf"

[generate-graph]
output = "graph_output.png"
figsize = { x = 10, y = 6 }