chamber = "30013"
clinical-pdd-zref = 67.5
energy = 6
fff = false
institution = "Hospital Oncológico Dr. Miguel Pérez Carreño"
k-elec = 1.000
m-reference = 11.8333
m-opposite = 11.909033120000002
m-reduced = 11.8333
measurement-date = "2025-05-16"
mu = 100
n-dw = 5.406
physicist = "Lic. Nelson Sandoval Puente"
press = [956.4, "mbar"]
setup = "SSD"
temp = 21.0
tissue-correction = 1.0
tpr2010 = 0.680
unit = "Elekta Precise"
voltage-reduced = -150
voltage-reference = -300
notes = ["Sample note 1.", "Sample note 2."]